spring.application.name=e-commerce-backend

server.port=5000

#spring.datasource.url=jdbc:h2:mem:test
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.defer-datasource-initialization=true
#spring.h2.console.enabled=true


#spring.data.mongodb.host=mongo-instance
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=e-commerce

spring.datasource.url=jdbc:mysql://e-commerce-db.cy7cmeqy8pmi.us-east-1.rds.amazonaws.com:3306/ecommerce_rds_db
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${AWS_RDS_USER}
spring.datasource.password=${AWS_RDS_PWD}
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.defer-datasource-initialization=true
spring.h2.console.enabled=false
